sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
  - '8'
  - '7'
before_install:
  - npm i -g npm@^2.0.0
install:
  - npm i -g codecov codeclimate-test-reporter semantic-release
  - npm i
before_script:
  - npm prune
script:
  - npm run travis
  - codecov
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
